### PR TITLE
Change ts_tumble UDF implementation to use TIMESTAMP_BUCKET function

### PR DESCRIPTION
**Pull request by avityuk**
Use the built-in [TIMESTAMP_BUCKET](https://cloud.google.com/bigquery/docs/reference/standard-sql/time-series-functions#timestamp_bucket) function in the implementation of ts_tumble UDF. Also add test cases for some edge cases.

### CODE REVIEW

**Comment by danieldeleo** [comment]
Please pull the latest changes from master branch which will resolve the build errors. Thanks!

**Comment by avityuk** [comment]
> Please pull the latest changes from master branch which will resolve the build errors. Thanks!

Done, thanks! Looks like I need another /gcbrun

**Review by danieldeleo — APPROVED** [review]

**Pull request merged**
