### PR TITLE
Add functions that implement SQL Server's convert expression

### PR DESCRIPTION
**Pull request by Hackerpilot**

### CODE REVIEW

**Comment by danieldeleo** [comment]
I see the PR is still in draft, but can you please change the sqlserver dataset abbreviation from `sq` to `ss`?

**Comment by Hackerpilot** [comment]
> I see the PR is still in draft, but can you please change the sqlserver dataset abbreviation from `sq` to `ss`?

Done.

**Review by afleisc — APPROVED** [review]

**Pull request merged**
